version: '3.8'

services:
  app:
    image: zenthurion/media-server-py-app:latest
    volumes:
      - .:/app:delegated
      - python-cache:/app/__pycache__
      - /run/user/1000/pulse:/run/user/1000/pulse
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHDOG_IGNORE_PATTERNS=__pycache__/*,*.pyc
      - DOCKER_ENV=1
      - ALSA_CARD=1
      - PULSE_SERVER=unix:/tmp/pulse-socket
    devices:
      - "/dev/snd:/dev/snd"
    group_add:
      - audio
    ports:
      - "8000:8000"
    command: python src/main.py
    tty: true
    stdin_open: true
    depends_on:
      - mqtt

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log

volumes:
  python-cache:
  mosquitto-data:
  mosquitto-logs: